Repository HYF-Class19/where-is-my-stuff-frontend, pull requests merged in 2023-04, with the labels that each got.

#43 Detailsmodalfix
  src/Modal/Details.tsx
  src/components/RemindersItem.tsx
Labels: Ionic component, Technical Development

#47 created calendar part
  src/components/Home/LendOut.tsx
Labels: documentation

#58 Lend backend
  package-lock.json
  package.json
  src/App.tsx
  src/components/Home/LendOut.tsx
  src/components/UserList.tsx
  src/db.ts
  src/pages/Lend.tsx
  src/pages/LoginPage.tsx
  tsconfig.json
Labels: Technical Development

#61 Lend backend
  src/Modal/ItemDetailsModal.tsx
  src/components/ItemDetails.tsx
  src/components/UserList.tsx
  src/pages/Lend.tsx
Labels: Technical Development

#62 Login page
  src/Modal/Toast.tsx
  src/db.ts
  src/firebase/auth.ts
  src/pages/LoginPage.tsx
Labels: Technical Development

#63 Lend-out backend
  src/components/Home/LendOut.tsx
Labels: Technical Development

#64 Loginbugfix
  src/components/Home/Navbar.tsx
  src/firebase/auth.ts
  src/pages/LoginPage.tsx
  src/useAuth.ts
Labels: bug

#68 Signupbutton fix
  src/pages/LoginPage.tsx
Labels: bug

#70 added new changes
  src/firebase/auth.ts
  src/pages/LoginPage.tsx
Labels: bug, Technical Development
