Repository HYF-Class19/where-is-my-stuff-frontend, pull requests merged in 2023-03, with the labels that each got.

#1 Planning
  README.md
  planning/README.md
  planning/backlog.md
  planning/communication-plan.md
  planning/constraits.md
  planning/design.md
  planning/development.md
  planning/retrospective.md
  planning/user-persona.md
Labels: documentation

#5 Planning
  .gitignore
  .vscode/extensions.json
  capacitor.config.ts
  ionic.config.json
  package-lock.json
  package.json
  planning/communication-plan.md
  planning/constraits.md
  planning/user-persona.md
  public/assets/icon/favicon.png
  public/assets/icon/icon.png
  public/assets/shapes.svg
  public/index.html
  public/manifest.json
  src/App.test.tsx
  src/App.tsx
  src/components/ExploreContainer.css
  src/components/ExploreContainer.tsx
  src/index.tsx
  src/pages/Home.css
  src/pages/Home.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  src/setupTests.ts
  src/theme/variables.css
  tsconfig.json
Labels: documentation

#11 add prototype in protototype.md file
  planning/5-proto-type.md
Labels: Design

#12 Planning
  planning/1-communication-plan.md
  planning/3-user-persona.md
  public/assets/logo.svg
Labels: documentation

#13 Planning
  README.md
  planning/1-communication-plan.md
  planning/assets/Lend (3) 1.png
  planning/assets/home.png
Labels: documentation

#15 add figma design
  planning/6-design.md
  planning/assets/Home.png
  planning/assets/Lend.png
  planning/assets/Reminder.png
  planning/assets/Trackmates.png
Labels: Design

#16 added information into backlog folder
  planning/4-backlog.md
Labels: documentation

#27 Planning
  README.md
  planning/7-development-strategy.md
  planning/assets/prototype.png
  planning/assets/screenshot.jpg
Labels: documentation, Design

#30 add footer
  src/components/Footer.tsx
Labels: Ionic component, Technical Development

#35 add back button in the IonModal
  src/components/UserList.tsx
Labels: Ionic component, Technical Development

#41 Reminders
  src/components/Footer.tsx
  src/components/RemindersItem.tsx
  src/hooks/UseReminder.ts
  src/pages/Reminder.tsx
  src/pages/styles/Reminder.css
  src/theme/variables.css
Labels: Ionic component, Technical Development

#40 created home page
  planning/assets/home.png
  public/assets/logo.png
  src/components/Home/LendOut.tsx
  src/components/Home/Menu.tsx
  src/components/Home/Navbar.css
  src/components/Home/Navbar.tsx
  src/pages/Home.tsx
  src/pages/styles/Home.css
  src/pages/styles/Reminder.css
Labels: Ionic component, Technical Development
